apiVersion: v1
kind: Service
metadata:
  name: auto-generator-service
spec:
  selector:
    app: auto-generator
  ports:
    - protocol: TCP
      nodePort: 30100
      port: 9008
      targetPort: 9008
  type: NodePort